# Generated by Django 3.2.8 on 2022-01-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=5)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
