# Generated by Django 3.2.8 on 2022-01-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=5)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member', serialize=False, to='users.customuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.room')),
            ],
        ),
    ]
